services:
  # A Docker web service
  - type: web
    name: tasks
    runtime: docker
    plan: free
    repo: https://github.com/JayMuppidi/TASKS # optional
    region: oregon # optional (defaults to oregon)
    branch: main # optional (defaults to master)
    dockerCommand: docker-compose up # optional (defaults to Dockerfile command)
   